[package]
name = "markdown_html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.10.0"
reqwest = { version = "0.11", features = ["blocking"] }
webbrowser = "0.8.12"


